export const FETCH_CAMPSITES_START = 'FETCH_CAMPSITES_START';
export const FETCH_CAMPSITES_SUCCESS = 'FETCH_CAMPSITES_SUCCESS';
export const FETCH_CAMPSITES_FAILURE = 'FETCH_CAMPSITES_FAILURE';

export const FETCH_PACKAGES_START = 'FETCH_PACKAGES_START';
export const FETCH_PACKAGES_SUCCESS = 'FETCH_PACKAGES_SUCCESS';
export const FETCH_PACKAGES_FAILURE = 'FETCH_PACKAGES_FAILURE';