export default [
    {
    id: "1",
    categoryId: "1",
    name: "Gourmet Smores",
    description: "No camping trip is complete without the traditional Smores! We've taken Smores to a whole new level with Jumbo marshmallows and gourmet dark chocolate.",
    price: 25,
    image: "https://media.istockphoto.com/photos/homemade-gooey-marshmallow-smores-picture-id535197090?k=6&m=535197090&s=612x612&w=0&h=M255uaTdnuFX_ESlOoXuRsi1Ra4wBEStkZFcVG8_J50=",
    },
    {
    id: "2",
    categoryId: "1",
    name: "Gourmet Hot Dogs",
    description: "That's right! Don't want to shop for dinner. Let us do it for you. The Gourmet Hot Dog kit includes Boar's head all beef hot dogs with your choice of toppings.",
    price: 50,
    image: "https://media.istockphoto.com/photos/gourmet-grilled-all-beef-hots-dogs-picture-id498099295?k=6&m=498099295&s=612x612&w=0&h=9vcLqfkffXVoxpWDmLKIVGuYUj0xHxPlaltflKpq11s=",
    },
    {
    id: "3",
    categoryId: "1",
    name: "Gourmet Hamburgers",
    description: "Treat yourself to real luxury with our Gourmet Hamburger Kit. We use only the highest quality meats and top it with the freshest ingrediants. No camping trip is complete without it!",
    price: 50,
    image: "https://img.grouponcdn.com/deal/26mYLy5sDuG3PKdMm883DbZVnxWs/26-2048x1229/v1/c700x420.jpg",
    },
    {
    id: "4",
    categoryId: "1",
    name: "Kayak",
    description: "As most of the campsites we offer sit off of a body of water, a true outdoors vacation is not complete without watersports! Get a one or two person kayak to complete your camping adventure.",
    price: 75,
    image: "https://images.pexels.com/photos/6529/lake-kajak-kayak.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    },
    {
    id: "5",
    categoryId: "1",
    name: "Propane Grill",
    description: "Worry-free camping is not complete without a propane grill. Although each campsite is fully equipped with charcoal grills, we can provide an easy-to-use propane grill and extra canister.",
    price: 50,
    image: "https://static.wixstatic.com/media/bf4a77_e7791799828f4024826fd6dd582e623e~mv2_d_3600_2400_s_4_2.jpg/v1/fill/w_1920,h_1040,al_c,q_90,usm_0.66_1.00_0.01/bf4a77_e7791799828f4024826fd6dd582e623e~mv2_d_3600_2400_s_4_2.webp",
    },
    {
    id: "6",
    categoryId: "1",
    name: "Breakfast In Bed",
    description: "Why wake up and worry about breakfast? With our Breakfast In Bed option we'll come to your campsite and make you a gourmet breakfast.",
    price: 100,
    image: "https://images.pexels.com/photos/139746/pexels-photo-139746.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    }
  ]