export default [
    {
    id: "1",
    categoryId: "1",
    name: "Amicalola Campground",
    tentDescription: "Combining luxury and the outdoors, our completely furnished 16ft Bell Tents are a vacationer's dream come true. An additional Queen bed may be added to your reservation during the checkout process for an additional fee. We will also provide up to two twin bed set-ups upon request. You are always welcome to bring extra sleeping bags.",
    campgroundDescription: "Amicalola State Park is nestled in the North Georgia Mountains, just outside of Dawsonville, Georgia. It is home to Georgia's tallest waterfall and the southernmost point of the Appalachian Trail.",
    price: 139,
    image: "/images/BellTent.jpg",
    },
    {
    id: "2",
    categoryId: "1",
    name: "Amicalola Campground",
    tentDescription: "Combining luxury and the outdoors, our completely furnished 16ft Bell Tents are a vacationer's dream come true. An additional Queen bed may be added to your reservation during the checkout process for an additional fee. We will also provide up to two twin bed set-ups upon request. You are always welcome to bring extra sleeping bags.",
    campgroundDescription: "Amicalola State Park is nestled in the North Georgia Mountains, just outside of Dawsonville, Georgia. It is home to Georgia's tallest waterfall and the southernmost point of the Appalachian Trail.",
    price: 139,
    image: "/images/BellTent.jpg",
    },
    {
    id: "3",
    categoryId: "1",
    name: "Amicalola Campground",
    tentDescription: "Combining luxury and the outdoors, our completely furnished 16ft Bell Tents are a vacationer's dream come true. An additional Queen bed may be added to your reservation during the checkout process for an additional fee. We will also provide up to two twin bed set-ups upon request. You are always welcome to bring extra sleeping bags.",
    campgroundDescription: "Amicalola State Park is nestled in the North Georgia Mountains, just outside of Dawsonville, Georgia. It is home to Georgia's tallest waterfall and the southernmost point of the Appalachian Trail.",
    price: 139,
    image: "/images/BellTent.jpg",
    },
    {
    id: "4",
    categoryId: "1",
    name: "Amicalola Campground",
    tentDescription: "Combining luxury and the outdoors, our completely furnished 16ft Bell Tents are a vacationer's dream come true. An additional Queen bed may be added to your reservation during the checkout process for an additional fee. We will also provide up to two twin bed set-ups upon request. You are always welcome to bring extra sleeping bags.",
    campgroundDescription: "Amicalola State Park is nestled in the North Georgia Mountains, just outside of Dawsonville, Georgia. It is home to Georgia's tallest waterfall and the southernmost point of the Appalachian Trail.",
    price: 139,
    image: "/images/BellTent.jpg",
    },
    {
    id: "5",
    categoryId: "1",
    name: "Amicalola Campground",
    tentDescription: "Combining luxury and the outdoors, our completely furnished 16ft Bell Tents are a vacationer's dream come true. An additional Queen bed may be added to your reservation during the checkout process for an additional fee. We will also provide up to two twin bed set-ups upon request. You are always welcome to bring extra sleeping bags.",
    campgroundDescription: "Amicalola State Park is nestled in the North Georgia Mountains, just outside of Dawsonville, Georgia. It is home to Georgia's tallest waterfall and the southernmost point of the Appalachian Trail.",
    price: 139,
    image: "/images/BellTent.jpg",
    },
    {
    id: "6",
    categoryId: "1",
    name: "Amicalola Campground",
    tentDescription: "Combining luxury and the outdoors, our completely furnished 16ft Bell Tents are a vacationer's dream come true. An additional Queen bed may be added to your reservation during the checkout process for an additional fee. We will also provide up to two twin bed set-ups upon request. You are always welcome to bring extra sleeping bags.",
    campgroundDescription: "Amicalola State Park is nestled in the North Georgia Mountains, just outside of Dawsonville, Georgia. It is home to Georgia's tallest waterfall and the southernmost point of the Appalachian Trail.",
    price: 139,
    image: "/images/BellTent.jpg",
    }
  ]