export default [
    {
    id: "1",
    categoryId: "1",
    name: "Amicalola Campground",
    tentDescription: "Combining luxury and the outdoors, our completely furnished 16ft Bell Tents are a vacationer's dream come true. An additional Queen bed may be added to your reservation during the checkout process for an additional fee. We will also provide up to two twin bed set-ups upon request. You are always welcome to bring extra sleeping bags.",
    campgroundDescription: "Amicalola State Park is nestled in the North Georgia Mountains, just outside of Dawsonville, Georgia. It is home to Georgia's tallest waterfall and the southernmost point of the Appalachian Trail.",
    price: 139,
    image: "https://images.pexels.com/photos/355637/pexels-photo-355637.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    },
    {
    id: "2",
    categoryId: "1",
    name: "Private Site",
    tentDescription: "Combining luxury and the outdoors, our completely furnished 16ft Bell Tents are a vacationer's dream come true. An additional Queen bed may be added to your reservation during the checkout process for an additional fee. We will also provide up to two twin bed set-ups upon request. You are always welcome to bring extra sleeping bags.",
    campgroundDescription: "In addition to the beautiful campground options available in Georgia, we can also bring our luxury tents to you. Perfect for birthday parties!",
    price: 139,
    image: "https://static.wixstatic.com/media/bf4a77_63dc6a1c516c435a93157f6c0f937f21~mv2_d_5811_3269_s_4_2.jpg/v1/fill/w_2400,h_1350,al_c,q_90,usm_0.66_1.00_0.01/bf4a77_63dc6a1c516c435a93157f6c0f937f21~mv2_d_5811_3269_s_4_2.webp",
    },
    {
    id: "3",
    categoryId: "1",
    name: "Shoal Creek Campground",
    tentDescription: "Combining luxury and the outdoors, our completely furnished 16ft Bell Tents are a vacationer's dream come true. An additional Queen bed may be added to your reservation during the checkout process for an additional fee. We will also provide up to two twin bed set-ups upon request. You are always welcome to bring extra sleeping bags.",
    campgroundDescription: "Shoal Creek is about seven miles from Lanier Islands. Campers will love the large wooded sites with tables, fire rings and grills. The views from the rustic walking trails are spectacular.",
    price: 139,
    image: "https://images.pexels.com/photos/462015/pexels-photo-462015.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    },
    {
    id: "4",
    categoryId: "1",
    name: "Unicoi Campground",
    tentDescription: "Combining luxury and the outdoors, our completely furnished 16ft Bell Tents are a vacationer's dream come true. An additional Queen bed may be added to your reservation during the checkout process for an additional fee. We will also provide up to two twin bed set-ups upon request. You are always welcome to bring extra sleeping bags.",
    campgroundDescription: "Unicoi State Park is one of the most popular parks in Georgia. Some of the many reasons why it attracts so many visitors includes the parks outstanding natural beauty, a wide range of amenities, and Unicoi State Park's proximity to the alpine village of Helen.",
    price: 139,
    image: "https://images.pexels.com/photos/302804/pexels-photo-302804.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    },
    {
    id: "5",
    categoryId: "1",
    name: "Vogel Campground",
    tentDescription: "Combining luxury and the outdoors, our completely furnished 16ft Bell Tents are a vacationer's dream come true. An additional Queen bed may be added to your reservation during the checkout process for an additional fee. We will also provide up to two twin bed set-ups upon request. You are always welcome to bring extra sleeping bags.",
    campgroundDescription: "One of Georgia’s oldest and most beloved state parks, Vogel is located at the base of Blood Mountain in the Chattahoochee National Forest. Driving from the south, visitors pass through Neel Gap, a beautiful mountain pass near Brasstown Bald, the highest point in Georgia.",
    price: 139,
    image: "https://static.wixstatic.com/media/bf4a77_09641440aadd49b99b2c861a6bbb7397~mv2_d_2048_1365_s_2.jpeg/v1/fill/w_909,h_606,al_c,q_90,usm_0.66_1.00_0.01/bf4a77_09641440aadd49b99b2c861a6bbb7397~mv2_d_2048_1365_s_2.webp",
    },
    {
    id: "6",
    categoryId: "1",
    name: "Suwanee Campground",
    tentDescription: "Combining luxury and the outdoors, our completely furnished 16ft Bell Tents are a vacationer's dream come true. An additional Queen bed may be added to your reservation during the checkout process for an additional fee. We will also provide up to two twin bed set-ups upon request. You are always welcome to bring extra sleeping bags.",
    campgroundDescription: "Sawnee Campground lies just north of the Buford Dam on Lake Sidney Lanier. The site features beautiful views of the lake as well as excellent access to boating and swimming. The lake, named for the poet, Sidney Lanier, is well known for its aqua-blue colored water, spectacular scenery and variety of recreational activities. Each year, over 9.5 million people come to visit.",
    price: 139,
    image: "https://static.wixstatic.com/media/bf4a77_4574a6f1a4d2423fad24dc6b7bd5a9f6~mv2.jpg/v1/fill/w_909,h_606,al_c,q_90,usm_0.66_1.00_0.01/bf4a77_4574a6f1a4d2423fad24dc6b7bd5a9f6~mv2.webp",
    }
  ]